%analyze power generated from STK sim for the purpose of CDR presentation
%goal: Find average power generated on three intervals: 
%                              -Max Beta
%                              -Min Beta
clear all
close all
power_min_beta_table = readtable('Power_Generated-Min_Beta_simple.csv');
power_max_beta_table = readtable('Power_Generated-Max_Beta_simple.csv');
power_avg_beta_table = readtable('Power_Generated-Avg_Beta_simple.csv');

min_beta_power = table2array(power_min_beta_table(:,1));
max_beta_power = table2array(power_max_beta_table(:,1));
avg_beta_power  =table2array(power_avg_beta_table(:,1));

%min_beta has many eclipse periods, filter those out for finding the power
%generation average
zero_times = find(min_beta_power ==0);
min_beta_power_noeclipse = min_beta_power;
for i = length(zero_times):-1:1
    if min_beta_power(zero_times(i)) ==0
        min_beta_power_noeclipse(zero_times(i)) = [];
    end
end

zero_times2 = find(avg_beta_power ==0);
avg_beta_power_noeclipse = avg_beta_power;
for i = length(zero_times2):-1:1
    if avg_beta_power(zero_times2(i)) ==0
        avg_beta_power_noeclipse(zero_times2(i)) = [];
    end
end

avg_power_min_beta = mean(min_beta_power_noeclipse);
avg_power_max_beta = mean(max_beta_power);
avg_power_avg_beta = mean(avg_beta_power_noeclipse);


plot(min_beta_power)
hold on
plot(xlim,[avg_power_min_beta avg_power_min_beta])
xlabel('Time [seconds]')
ylabel('Total Power Generated [W]')
title('Minimum Beta Angle (Worst Case) Power Generation')
legend('Power generated by solar panels','Average Power Generation')

figure
plot(max_beta_power)
hold on
plot(xlim,[avg_power_max_beta avg_power_max_beta])
xlabel('Time [seconds]')
ylabel('Total Power Generated [W]')
title('Maximum Beta Angle (Best Case) Power Generation')
legend('Power generated by solar panels','Average power generation')
hold off

figure
plot(avg_beta_power)
hold on
plot(xlim,[avg_power_avg_beta avg_power_avg_beta])
xlabel('Time [seconds]')
ylabel('Total Power Generated [W]')
title('Average Beta Angle (Nominal Case) Power Generation')
legend('Power generated by solar panels','Average power generation')
hold off